---
# tasks file for roles/iti_web_servers

- name: update_cache  and install nginx
  ansible.builtin.yum:
  #don't need loop yum->install list of app
    name: "{{ nginx_packge }}" 
    state: present
    update_cache: yes


- name: start and enable service nginx
  ansible.builtin.service:
    name: "{{nginx_service}}"
    enabled: yes
    state: started

- name: add custom root page
  ansible.builtin.template:
    src: index.html.j2
    dest: "{{ nginx_html_dir }}/index.html"
    mode: 0644
  notify: 
    - restart nginx service  

- name: Copy css file
  ansible.builtin.copy:
    src: css
    dest: /usr/share/nginx/html
    mode: 0644

